@startuml conflict-resolution-sequence-diagram
!include style.puml

box View VIEW_BACKGROUND_COLOR
participant ":DocumentEditViewController" as DocumentEditViewController VIEW_COLOR
end box

box Presenter PRESENTER_BACKGROUND_COLOR
participant ":DocumentPresenter" as DocumentPresenter PRESENTER_COLOR
end box

box Interactor INTERACTOR_BACKGROUND_COLOR
participant ":DocumentsInteractor" as DocumentsInteractor INTERACTOR_COLOR
end box

box ConflictResolver OTHER_BACKGROUND_COLOR
participant ":ConflictResolver" as ConflictResolver OTHER_COLOR
end box

box Persistence ENTITY_BACKGROUND_COLOR
participant ":LocalDocumentsPersistence" as LocalDocumentsPersistence ENTITY_COLOR
participant ":RemoteDocumentsPersistence" as RemoteDocumentsPersistence ENTITY_COLOR
end box

[-> DocumentEditViewController : viewWillAppear(animated)
activate DocumentEditViewController

DocumentEditViewController --> DocumentEditViewController : initializeSubviews()
activate DocumentEditViewController

DocumentEditViewController --> DocumentPresenter : loadDocumentWithDeleted(documentId)
activate DocumentPresenter

DocumentPresenter --> DocumentsInteractor : loadResolvedDocument(documentId)
activate DocumentsInteractor

DocumentsInteractor --> DocumentsInteractor : getLocalAndRemoteDocument(documentId)
activate DocumentsInteractor

DocumentsInteractor --> LocalDocumentsPersistence : getDocument(documentId)
activate LocalDocumentsPersistence

LocalDocumentsPersistence ---> DocumentsInteractor : localDocument
deactivate LocalDocumentsPersistence

DocumentsInteractor --> RemoteDocumentsPersistence : getDocument(documentId)
activate RemoteDocumentsPersistence

RemoteDocumentsPersistence ---> DocumentsInteractor : localDocument
deactivate RemoteDocumentsPersistence

DocumentsInteractor ---> DocumentsInteractor : (localDocument, remoteDocument)
deactivate DocumentsInteractor

create ConflictResolver
DocumentsInteractor --> ConflictResolver : init(localAnnotations, remoteAnnotations)
activate ConflictResolver

ConflictResolver ---> DocumentsInteractor
deactivate ConflictResolver

DocumentsInteractor --> ConflictResolver : resolve()
activate ConflictResolver

ref over ConflictResolver : Conflict Resolution

ConflictResolver ---> DocumentsInteractor
deactivate ConflictResolver

DocumentsInteractor ---> DocumentPresenter
deactivate DocumentsInteractor

DocumentPresenter ---> DocumentEditViewController
deactivate DocumentPresenter

DocumentEditViewController ---> DocumentEditViewController
deactivate DocumentEditViewController

DocumentEditViewController --->[
deactivate DocumentEditViewController

@enduml
