@startuml add-annotation-sequence-diagram
!include style.puml

box Actor
actor User as User USER_COLOR
end box

box View VIEW_BACKGROUND_COLOR
participant ":DocumentView" as DocumentView VIEW_COLOR
end box

box View Model INTERACTOR_BACKGROUND_COLOR
participant ":DocumentViewModel" as DocumentViewModel INTERACTOR_COLOR
participant ":AnnotationViewModel" as AnnotationViewModel INTERACTOR_COLOR
end box

box Model ENTITY_BACKGROUND_COLOR
participant ":Document" as Document INTERACTOR_COLOR
end box

User -> DocumentView : didTap(sender)
activate DocumentView

DocumentView -> DocumentView : addAnnotation(pointInDocument)
activate DocumentView

DocumentView -> DocumentViewModel : addAnnotation(center)
activate DocumentViewModel

DocumentViewModel -> Document : addAnnotation()
activate Document
Document --> DocumentViewModel
deactivate Document

create AnnotationViewModel
DocumentViewModel -> AnnotationViewModel : AnnotationViewModel(annotation)
activate AnnotationViewModel

AnnotationViewModel --> DocumentViewModel : annotationViewModel
deactivate AnnotationViewModel

DocumentViewModel --> DocumentView
deactivate DocumentViewModel

DocumentView --> DocumentView
deactivate DocumentView

DocumentView --> DocumentView
deactivate DocumentView

DocumentViewModel -> DocumentView : notify observer
activate DocumentView

DocumentView -> DocumentView : renderNewAnnotation(annotationViewModel)
activate DocumentView

DocumentView --> DocumentView
deactivate DocumentView

DocumentView --> DocumentView
deactivate DocumentView

@enduml
