@startuml

!include style.puml

' Shared
Class WebSocketManager WEBSOCKET_COLOR {
    socket
    @Published message
    --
    setUpSocket()
    resetSocket()
    listen()
    send(message)
    publishResponseData(data)
}

Class RootInteractor INTERACTOR_COLOR {
    @Published crudDocumentMessage
    @Published crudAnnotationMessage
    --
    publishMessage(decodedMessageType, message)
}

' Annotations
package "Annotations Persistence" {
    Class AnnotationsInteractor INTERACTOR_COLOR {
        --
        createAnnotation(annotation)
        updateAnnotation(annotation)
        deleteAnnotation(annotation)
        createOrUpdateAnnotation(annotation)

        // Conflict resolution persistence
        persistConflictResolution(conflictResolution: ConflictResolution<Annotation>)
    }

    package "Remote Annotations Persistence Service" {
        Class RemoteAnnotationsPersistence PERSISTENCE_COLOR {
            --
            createAnnotation(annotation, senderId)
            updateAnnotation(annotation, senderId)
            deleteAnnotation(annotation, senderId)
            createOrUpdateAnnotation(annotation, senderId)
        }
        RemoteAnnotationsPersistence --down> WebSocketManager
    }

    package "Local Annotations Persistence Service" {
        Class LocalAnnotationsPersistence PERSISTENCE_COLOR {
            --
            createAnnotation(annotation)
            updateAnnotation(annotation)
            deleteAnnotation(annotation)
            createOrUpdateAnnotation(annotation)
        }

        Class LocalAnnotationsEntityDataAccess DATAACCESS_COLOR {
            context
            --
            listCreatedAfterDate(date)
            listUpdatedAfterDate(date)
            create(annotation)
            read(annotationId, withDeleted)
            readInCurrentContext(annotationId, withDeleted)
            update(annotationId, annotation)
            delete(annotationId, annotation)
        }

        entity "Annotations Core Data Entities" ENTITY_COLOR
        note "Shown in a separate diagram" as N2
        "Annotations Core Data Entities" ..left N2

        LocalAnnotationsEntityDataAccess ..down> "Annotations Core Data Entities"
        LocalAnnotationsPersistence --down> "1" LocalAnnotationsEntityDataAccess
    }
    AnnotationsInteractor --down> "1" RemoteAnnotationsPersistence
    AnnotationsInteractor --down> "1" LocalAnnotationsPersistence
    AnnotationsInteractor --down> "1 | subscribes to" RootInteractor
}

@enduml