@startuml delete-document-share-sequence-diagram
!include style.puml

box View VIEW_BACKGROUND_COLOR
participant ":DocumentListViewController" as DocumentListViewController VIEW_COLOR
end box

box Presenter PRESENTER_BACKGROUND_COLOR
participant ":DocumentListPresenter" as DocumentListPresenter PRESENTER_COLOR
end box

box Interactor INTERACTOR_BACKGROUND_COLOR
participant ":DocumentSharesInteractor" as DocumentSharesInteractor INTERACTOR_COLOR
end box

box Persistence ENTITY_BACKGROUND_COLOR
participant ":RemoteDocumentSharesPersistence" as RemoteDocumentSharesPersistence ENTITY_COLOR
participant ":LocalDocumentsPersistence" as LocalDocumentsPersistence ENTITY_COLOR
end box

[->  DocumentListViewController : didTapDeleteAsNonOwner()
activate DocumentListViewController

DocumentListViewController -> DocumentListPresenter : deleteDocumentAsNonOwner(document)
activate DocumentListPresenter

DocumentListPresenter -> DocumentSharesInteractor : deleteDocumentShare(document, recipientId)
activate DocumentSharesInteractor

DocumentSharesInteractor -> RemoteDocumentSharesPersistence : deleteDocumentShare(documentId, recipientId)
activate RemoteDocumentSharesPersistence

RemoteDocumentSharesPersistence --> DocumentSharesInteractor
deactivate RemoteDocumentSharesPersistence

DocumentSharesInteractor -> LocalDocumentsPersistence : deleteDocument(document)
activate LocalDocumentsPersistence

LocalDocumentsPersistence --> DocumentSharesInteractor
deactivate LocalDocumentsPersistence

DocumentSharesInteractor --> DocumentListPresenter
deactivate DocumentSharesInteractor

DocumentListPresenter --> DocumentListViewController
deactivate DocumentListPresenter

[<-- DocumentListViewController
deactivate DocumentListViewController

@enduml
