@startuml

!include style.puml

package "Document Shares" {
    Class DocumentCodeImportViewController VIEW_COLOR {
        --
        didTapImportButton()
        importDocument()
    }

    Class DocumentSharesPresenter PRESENTER_COLOR {
        --
        createDocumentShare(documentId)
    }

    Class AuthPresenter PRESENTER_COLOR {
        currentUser: AnnotatoUser
    }

    Class DocumentSharesInteractor INTERACTOR_COLOR {
        --
        createDocumentShare(documentShare)
        deleteDocumentShare(document, receipendId)
    }

    Class DocumentShare MODEL_COLOR {
        id
        documentId
        receipendId
    }

    Class RemoteDocumentSharesPersistence PERSISTENCE_COLOR {
        --
        createDocumentShare(documentShare)
        deleteDocumentShare(documentId, receipendId)
        ...
    }

    Class localDocumentSharesPersistence PERSISTENCE_COLOR {
        --
        createDocumentShare(documentShare)
        deleteDocumentShare(documentId, receipendId)
        ...
    }
}

DocumentSharesInteractor ..left> DocumentShare
DocumentSharesInteractor --down> "1" RemoteDocumentSharesPersistence
DocumentSharesInteractor --down> "1  " localDocumentSharesPersistence

DocumentSharesPresenter ..left> AuthPresenter
DocumentCodeImportViewController --down> "1" DocumentSharesPresenter
DocumentSharesPresenter --down> "1" DocumentSharesInteractor

@enduml
