@startuml

package "Document List" {
    Class DocumentListViewController {
        toolbar: DocumentListToolbarView
        importMenu: DocumentListImportMenu
        --
        // Navigating between views
        didTapLogOutButton()
        didTapImportFromIpadButton()
        didTapImportFromCodeButton()
        didSelectCellView(document)

        // Delete document functionality
        didLongPressCellView() // Enters delete mode
        didTapExitDeleteModeButton()
        didTapDeleteForEveryoneButton(document)
        didTapDeleteAsNonOwner(document)
        didTapChangeOwnerButton(document)
    }

    Class DocumentListCollectionView {
        isInDeleteMode: Bool
        --
        enterDeleteMode()
        exitDeleteMode()
    }

    Class DocumentListCollectionCellView { }

    Class DocumentListCellPresenter {
        document: Document
        --
        canFindUsersSharingDocument() -> Bool
    }

    Class UsersInteractor {
        --
        createUser(user: AnnotatoUser)
        getUser(userId)
        getUsersSharingDocument(documentId)
        saveSessionUser(user: AnnotatoUser)
        fetchSessionUser()
        purgeSessionUser()
    }

    Class AnnotatoUser {
        email
        displayName
        id
    }
}

DocumentListViewController --down> "1 " DocumentListCollectionView
DocumentListCollectionView --down> "*" DocumentListCellPresenter
DocumentListCollectionView ..left> "*" DocumentListCollectionCellView
DocumentListCollectionCellView --down> "1 " DocumentListCellPresenter
DocumentListCellPresenter --down> "1" UsersInteractor
UsersInteractor ..right> AnnotatoUser

@enduml
