@startuml import-from-code-sequence-diagram
!include style.puml

actor User as User USER_COLOR

box View VIEW_BACKGROUND_COLOR
participant ":DocumentListViewController" as DocumentListViewController VIEW_COLOR
participant ":DocumentCodeImportViewController" as DocumentCodeImportViewController VIEW_COLOR
end box

box Presenter PRESENTER_BACKGROUND_COLOR
participant ":DocumentSharePresenter" as DocumentSharePresenter PRESENTER_COLOR
end box

box Model MODEL_BACKGROUND_COLOR
participant ":DocumentShare" as DocumentShare MODEL_COLOR
end box

box Interactor INTERACTOR_BACKGROUND_COLOR
participant ":DocumentSharesInteractor" as DocumentSharesInteractor INTERACTOR_COLOR
end box

box Persistence ENTITY_BACKGROUND_COLOR
participant ":LocalDocumentsPersistence" as LocalDocumentsPersistence ENTITY_COLOR
participant ":RemoteDocumentSharesPersistence" as RemoteDocumentSharesPersistence ENTITY_COLOR
end box

User -> DocumentListViewController : didTapFromCodeButton()
activate DocumentListViewController

DocumentListViewController -> DocumentListViewController : goToImportByCode()
activate DocumentListViewController

create DocumentCodeImportViewController
DocumentListViewController -> DocumentCodeImportViewController
activate DocumentCodeImportViewController

DocumentCodeImportViewController --> DocumentListViewController
deactivate DocumentCodeImportViewController

User -> DocumentCodeImportViewController : didTapImportButton(sender)
activate DocumentCodeImportViewController

DocumentCodeImportViewController -> DocumentCodeImportViewController : importDocument()
activate DocumentCodeImportViewController

DocumentCodeImportViewController -> DocumentSharePresenter : createDocumentShare(documentId)
activate DocumentSharePresenter

create DocumentShare
DocumentSharePresenter -> DocumentShare : init(documentId, currentUserId)
activate DocumentShare

DocumentShare --> DocumentSharePresenter : documentShare
deactivate DocumentShare

DocumentSharePresenter -> DocumentSharesInteractor : createDocumentShare(documentShare)
activate DocumentSharesInteractor

DocumentSharesInteractor -> RemoteDocumentSharesPersistence : createDocumentShare(documentShare)
activate RemoteDocumentSharesPersistence

RemoteDocumentSharesPersistence --> DocumentSharesInteractor : remoteDocument
deactivate RemoteDocumentSharesPersistence

DocumentSharesInteractor -> LocalDocumentsPersistence : createDocument(remoteDocument)
activate LocalDocumentsPersistence

LocalDocumentsPersistence --> DocumentSharesInteractor : localSharedDocument
deactivate LocalDocumentsPersistence

DocumentSharesInteractor --> DocumentSharePresenter : localSharedDocument
deactivate DocumentSharesInteractor

DocumentSharePresenter --> DocumentCodeImportViewController
deactivate DocumentSharePresenter

DocumentCodeImportViewController --> DocumentCodeImportViewController
deactivate DocumentCodeImportViewController

DocumentCodeImportViewController --> User
deactivate DocumentCodeImportViewController

DocumentListViewController --> DocumentListViewController
deactivate DocumentListViewController

DocumentListViewController --> User
deactivate DocumentListViewController

@enduml
