@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor ENTITY_COLOR
skinparam classBackgroundColor ENTITY_COLOR

Package Models {
    Class User {
        uid: String
        email: String
        displayName: String
    }

    Class Document {
        id: UUID
        name: String
        ownerId: String
        baseFileUrl: String
    }

    Class Annotation {
        id: UUID
        origin: Point
        width: Double
        ownerId: String
        documentId: UUID
    }

    Interface AnnotationPart <<protocol>> {
        id: UUID
        order: Int
        height: Double
        annotationId: UUID
        isEmpty: Bool
        --
        remove()
    }

    Class AnnotationText {
        type: AnnotationText.TextType
        content: String
    }

    Class AnnotationHandwriting {
        handwriting: Data
    }

    Class SelectionBox {
        id: UUID
        startPoint: CGPoint
        endPoint: CGPoint
        annotationId: UUID
    }

    Class DocumentShare {
        id: UUID
        documentId: UUID
        recipientId: String
    }

    User "owner" *--> "*" Document
    User "recipient\n0..*" -- "0..*" Document
    (Document, User) . DocumentShare
    Document *-> "*" Annotation
    Annotation *-> "*" AnnotationPart
    AnnotationHandwriting .up.|> AnnotationPart
    AnnotationText .up.|> AnnotationPart
    Annotation *-> "1" SelectionBox
}



@enduml
