@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor ENTITY_COLOR
skinparam classBackgroundColor ENTITY_COLOR

Package "Shared Library Models" {
    Class User {
        uid: String
        email: String
        displayName: String
    }

    Class Document {
        id: UUID
        name: String
        ownerId: String
        baseFileUrl: String
    }

    Class Annotation {
        id: UUID
        origin: Point
        width: Double
        ownerId: String
        documentId: UUID
    }

    Interface AnnotationPart <<protocol>> {
        id: UUID
        order: Int
        height: Double
        annotationId: UUID
        isEmpty: Bool
        --
        remove()
    }

    Class AnnotationText {
        type: AnnotationText.TextType
        content: String
    }

    Class AnnotationHandwriting {
        handwriting: Data
    }

    Class SelectionBox {
        id: UUID
        startPoint: CGPoint
        endPoint: CGPoint
        annotationId: UUID
    }

    Class DocumentShare {
        id: UUID
        documentId: UUID
        recipientId: String
    }

    Interface Timestampable <<protocol>> {
        createdAt: Date?
        updatedAt: Date?
        deletedAt: Date?
        --
        wasCreatedAfter(date: Date): Bool
        wasUpdatedAfter(date: Date): Bool
    }

    User "owner" *-> "*" Document
    User "recipient\n0..*" -- "0..*" Document
    (Document, User) . DocumentShare
    Document *-down-> "*" Annotation
    Annotation *-down> "*" AnnotationPart
    AnnotationHandwriting .up.|> AnnotationPart
    AnnotationText .up.|> AnnotationPart
    Annotation *-> "1" SelectionBox

    User .up|> Timestampable
    DocumentShare .up|> Timestampable
    Document .up|> Timestampable
    Annotation .up|> Timestampable
    SelectionBox .up|> Timestampable
    AnnotationPart -up|> Timestampable
}



@enduml
