@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor ENTITY_COLOR
skinparam classBackgroundColor ENTITY_COLOR

Package Storage {
    Interface AnnotatoStorageService <<protocol>> {
        --
        uploadPdf(fileSystemUrl: URL, fileName: String)
        deletePdf(fileName: String)
    }

    Class PDFStorageManager {
        --
        uploadPdf(fileSystemUrl: URL, fileName: String)
        deletePdf(fileName: String)
    }

    Class FirebaseStorage {
        ( - ) storage: Firebase.Storage
        ( - ) storageRef: Firebase.StorageReference
        --
        uploadPdf(fileSystemUrl: URL, fileName: String)
        deletePdf(fileName: String)
        getDownloadURL(documentId: UUID)
    }

    Class LocalStorage {
        appDocumentsDirectory: URL
        --
        uploadPdf(fileSystemUrl: URL, fileName: String)
        uploadPdf(pdfData: Data, fileName: String)
        deletePdf(fileName: String))
    }
}

PDFStorageManager *--> "localStorageService" AnnotatoStorageService
PDFStorageManager *--> "remoteStorageService" AnnotatoStorageService

FirebaseStorage .up.|> AnnotatoStorageService
LocalStorage .up.|> AnnotatoStorageService
LocalStorage -[hidden]right-> FirebaseStorage

@enduml
