@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor ENTITY_COLOR
skinparam classBackgroundColor ENTITY_COLOR

Package "PDF Storage" {
    Interface AnnotatoRemoteStorageService <<protocol>> {
        --
        getDownloadUrl(fileName: String): URL?
        uploadPdf(fileSystemUrl: URL, fileName: String)
        deletePdf(fileName: String)
    }

    Interface AnnotatoLocalStorageService <<protocol>> {
        --
        getUrl(fileName: String): URL
        uploadPdf(fileSystemUrl: URL, fileName: String)
        uploadPdf(pdfData: Data, fileName: String)
        deletePdf(fileName: String)
    }

    Class PDFStorageManager {
        --
        getLocalUrl(fileName: String): URL
        uploadPdf(fileSystemUrl: URL, fileName: String)
        downloadPdfToLocalStorage(fileName: String)
        deletePdf(fileName: String)
    }

    Class FirebaseStorage {
        ( - ) storage: Firebase.Storage
        ( - ) storageRef: Firebase.StorageReference
        --
        getDownloadUrl(fileName: String): URL?
        uploadPdf(fileSystemUrl: URL, fileName: String)
        deletePdf(fileName: String)
    }

    Class LocalStorage {
        appDocumentsDirectory: URL
        --
        getUrl(fileName: String): URL
        uploadPdf(fileSystemUrl: URL, fileName: String)
        uploadPdf(pdfData: Data, fileName: String)
        deletePdf(fileName: String)
    }
}

PDFStorageManager *--> "localStorageService" AnnotatoLocalStorageService
PDFStorageManager *--> "remoteStorageService" AnnotatoRemoteStorageService

FirebaseStorage .up.|> AnnotatoRemoteStorageService
LocalStorage .up.|> AnnotatoLocalStorageService

LocalStorage -[hidden]right-> FirebaseStorage

@enduml
