@startuml update-annotation-start-from-user-sequence-diagram
!include style.puml

actor User as User USER_COLOR

box View VIEW_BACKGROUND_COLOR
participant ":AnnotationPaletteView" as AnnotationPaletteView VIEW_COLOR
end box

box Presenter PRESENTER_BACKGROUND_COLOR
participant ":AnnotationPalettePresenter" as AnnotationPalettePresenter PRESENTER_COLOR
participant ":AnnotationPresenter" as AnnotationPresenter PRESENTER_COLOR
end box

box Interactor INTERACTOR_BACKGROUND_COLOR
participant ":AnnotationsInteractor" as AnnotationsInteractor INTERACTOR_COLOR
end box

box Persistence ENTITY_BACKGROUND_COLOR
participant ":LocalAnnotationsPersistence" as LocalAnnotationsPersistence ENTITY_COLOR
participant ":RemoteAnnotationsPersistence" as RemoteAnnotationsPersistence ENTITY_COLOR
end box

User -> AnnotationPaletteView : didTapEditOrViewButton(button)
activate AnnotationPaletteView
opt !isNowEditing

AnnotationPaletteView -> AnnotationPalettePresenter : enterViewMode()
activate AnnotationPalettePresenter

AnnotationPalettePresenter -> AnnotationPresenter : enterViewMode()
activate AnnotationPresenter

AnnotationPresenter -> AnnotationsInteractor : updateAnnotation(annotation)
activate AnnotationsInteractor

AnnotationsInteractor -> RemoteAnnotationsPersistence : createAnnotation(annotation, senderId)
activate RemoteAnnotationsPersistence

RemoteAnnotationsPersistence --> AnnotationsInteractor
deactivate RemoteAnnotationsPersistence

AnnotationsInteractor -> LocalAnnotationsPersistence : createAnnotation(annotation)
activate LocalAnnotationsPersistence

LocalAnnotationsPersistence --> AnnotationsInteractor
deactivate LocalAnnotationsPersistence

AnnotationsInteractor --> AnnotationPresenter
deactivate AnnotationsInteractor

AnnotationPresenter --> AnnotationPalettePresenter
deactivate AnnotationPresenter

AnnotationPalettePresenter --> AnnotationPaletteView
deactivate AnnotationPalettePresenter

AnnotationPaletteView --> User
deactivate AnnotationPaletteView

end

@enduml
