# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'Annotato' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Annotato
  pod 'Firebase/Auth', '8.12.1'
  pod 'SwiftyBeaver', '1.9.5'
  pod 'RichTextView', '3.2.1'
end
