include:
  - settings.yml
attributes:
  LastSwiftUpdateCheck: 1320
  LastUpgradeCheck: 1320
configs:
  Debug: debug
  Release: release
name: Annotato
options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
schemes:
  Annotato:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        Annotato:
          - running
          - testing
          - profiling
          - analyzing
          - archiving
    profile:
      config: Release
    run:
      config: Debug
settings:
  configs:
    Debug:
      CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
      IPHONEOS_DEPLOYMENT_TARGET: 15.2
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: YES
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
      IPHONEOS_DEPLOYMENT_TARGET: 15.2
      MTL_FAST_MATH: YES
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
packages:
  AnnotatoBackend:
    path: ../AnnotatoBackend
  AnnotatoSharedLibrary:
    path: ../AnnotatoSharedLibrary
targets:
  Annotato:
    platform: iOS
    dependencies:
      - package: AnnotatoSharedLibrary
    postbuildScripts:
      - runOnlyWhenInstalling: false
        script:
          "# Homebrew install location for ARM\nPATH=${PATH}:/opt/homebrew/bin\n\nif
          which swiftlint >/dev/null; then\n    swiftlint autocorrect --config ../.swiftlint.yml && swiftlint --config ../.swiftlint.yml && cd ../AnnotatoBackend && swiftlint autocorrect --config ../.swiftlint.yml && swiftlint --config ../.swiftlint.yml && cd ../AnnotatoSharedLibrary && swiftlint autocorrect --config ../.swiftlint.yml && swiftlint --config ../.swiftlint.yml\nelse\n
          \ echo \"warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint\"\nfi\n"
        shell: /bin/sh
    settings:
      configs:
        Debug:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: Annotato/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 15.2
          PROVISIONING_PROFILE_SPECIFIER:
          SWIFT_VERSION: 5.5.3
          TARGETED_DEVICE_FAMILY: 2
        Release:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: Annotato/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 15.2
          PROVISIONING_PROFILE_SPECIFIER:
          SWIFT_VERSION: 5.5.3
          TARGETED_DEVICE_FAMILY: 2
    sources:
      - name: Annotato
        path: Annotato
    type: application
