name: SwiftLint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2
      - name: Run SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --config .swiftlint.yml --strict
